_commit: 2d9c935
_src_path: /home/nlesc/github/jspaaks/copier-template-for-c-projects
add_answers: true
add_assets: false
add_clang_format: true
add_cmake: true
add_codeblocks: true
add_external: false
add_test: true
build_directory: built
c_std: c_std_90
exename: navigator
libname: operations
libpurpose: both
nested: true
producesexe: true
produceslib: true
projectname: navigator-project
