name: dbg

on:
  push:
    branches:
      - main

jobs:

  testing:
    name: py${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'windows-2022' ]
        python-version: ['3.12']
    steps:

      - name: Install dependencies for building Criterion
        run: |
          choco install meson -y
          choco install ninja -y

      - name: Show versions
        run: |
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          refreshenv
          meson --version
          ninja --version

      - name: Download, build and install Criterion
        run: |
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          refreshenv
          Invoke-WebRequest -Uri https://github.com/Snaipe/Criterion/archive/refs/tags/v2.4.2.tar.gz -OutFile Criterion-2.4.2.tar.gz
          tar -xvf Criterion-2.4.2.tar.gz
          cd Criterion-2.4.2
          meson setup build .
          meson install -C build

      - name: (windows-2022) Desperate try to allow long pathnames
        run: git config --system core.longpaths true

      - name: Get a copy of the repository contents
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Python version
        run: |
          which python
          python --version

      - name: Upgrade pip, setuptools and wheel
        run: python -m pip install --upgrade pip setuptools wheel

      - name: (windows-2022) Run fuzzy tests for standard C17
        run: |
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          refreshenv
          python -m venv venv
          venv\Scripts\Activate.ps1
          python -m pip install .[testing]
          $Env:NFUZZY='100'
          $Env:CMAKE_C_STANDARD='c_std_17'
          python -m pytest -rA --verbose
